import {
  Avatar3,
  Avatar6,
  Avatar2,
  Avatar4,
  Avatar5,
  Avatar7,
  Avatar8,
  Avatar9,
} from "@/assets/images/users/utils";

export const contacts: { [key: string]: any }[] = [
  {
    avatar: Avatar2,
    name: "Patricia Honda",
    designation: "Full Stack Developer",
    phone: "617 219 6245",
    email: "patriciahonda@steex.com",
    location: "2995 Lynn Street Newton, MA 02160",
  },
  {
    avatar: Avatar3,
    name: "James Lash",
    designation: "Web Designer",
    phone: "617 219 6245",
    email: "jameslash@steex.com",
    location: "3089 Leroy Lane Pollock, SD 57648",
  },
  {
    avatar: Avatar4,
    name: "Angus Garnsey",
    designation: "React Developer",
    phone: "085 383 2388",
    email: "angusgarnsey@steex.com",
    location: "1738 Old Cres Lady Frere 5411",
    isInactive: true,
  },
  {
    avatar: Avatar5,
    name: "Matilda Marston",
    designation: "Shopify Developer",
    phone: "082 288 1065",
    email: "matildamarston@steex.com",
    location: "2168 Bezuidenhout St Evander 2270",
    isInactive: false,
  },
  {
    avatar: Avatar6,
    name: "Zachary Benjamin",
    designation: "Shopify Developer",
    phone: "348 9730237",
    email: "zacharybenjamin@steex.com",
    location: "Via Carlo Alberto, 8 22020-Faloppio CO",
  },
  {
    avatar: Avatar7,
    name: "Ruby Chomley",
    designation: "Shopify Developer",
    phone: "348 9730237",
    email: "rubychomley@steex.com",
    location: "Via Pasquale Scura, 76 75010-Calciano MT",
  },
  {
    avatar: Avatar7,
    name: "Sophia Prendiville",
    designation: "Angular Developer",
    phone: "0354 3037376",
    email: "sophiaprendiville@steex.com",
    location: "36078-Maglio Di Sopra VI",
  },
  {
    avatar: Avatar8,
    name: "Samantha Zepps",
    designation: "Project Manager",
    phone: "0365 4363346",
    email: "samanthazepps@steex.com",
    location: "Via del Carmine, 108 36040-Sarego VI",
  },
  {
    avatar: Avatar9,
    name: "Xavier Bower",
    designation: "Graphic Designer",
    phone: "0486 45 08 27",
    email: "xavierbower@steex.com",
    location: "Rue Haute 47 8630 Steenkerke",
  },
];
