import {
  Avatar1,
  Avatar2,
  Avatar3,
  Avatar4,
  Avatar5,
  Avatar6,
  Avatar7,
  Avatar8,
  Avatar9,
  Avatar10,
} from "@/assets/images/users/utils";
import { AgentListingType } from "@/components/realEstate/agent/types";
import { MenuSelectItemType } from "@/app/common/components/filters/types";

export const agentListingData: AgentListingType[] = [
  {
    id: 1,
    joining_date: "19 Nov, 2022",
    img: Avatar1,
    img_alt: "avatar-1.jpg",
    name: "Dianna Bogan",
    property: "149",
    location: "Brasília, Brazil",
    email: "dianna@steex.com",
    contact: "(86) 9985-9220",
    status: "active",
    new: true,
  },
  {
    id: 2,
    joining_date: "25 Nov, 2022",
    img: Avatar10,
    img_alt: "avatar-10.jpg",
    name: "Josefa Weissnat",
    property: "164",
    location: "California, USA",
    email: "josefaweissnat@steex.com",
    contact: "(53) 3035-3100",
    status: "unActive",
    new: false,
  },
  {
    id: 3,
    joining_date: "08 Dec, 2022",
    img: Avatar9,
    img_alt: "avatar-9.jpg",
    name: "Ophelia Steuber",
    property: "279",
    location: "Sobrado, Spain",
    email: "opheliasteuber@steex.com",
    contact: "(21) 2345-6789",
    status: "active",
    new: false,
  },
  {
    id: 4,
    joining_date: "21 Dec, 2022",
    img: Avatar8,
    img_alt: "avatar-8.jpg",
    name: "Federico Hand",
    property: "487",
    location: "San Luis Potosi, Mexico",
    email: "federico@steex.com",
    contact: "(11) 3666-9716",
    status: "active",
    new: false,
  },
  {
    id: 5,
    joining_date: "27 Jan, 2023",
    img: Avatar7,
    img_alt: "avatar-7.jpg",
    name: "Uriel King",
    property: "369",
    location: "Ibiza, Spain",
    email: "urielking@steex.com",
    contact: "(92) 3639-8685",
    status: "unActive",
    new: true,
  },
  {
    id: 6,
    joining_date: "18 Feb, 2023",
    img: Avatar6,
    img_alt: "avatar-6.jpg",
    name: "Buck Roberts",
    property: "495",
    location: "Guarulhos, Brazil",
    email: "buckroberts@steex.com",
    contact: "(11) 3885-1022",
    status: "active",
    new: false,
  },
  {
    id: 7,
    joining_date: "24 Feb, 2023",
    img: Avatar5,
    img_alt: "avatar-5.jpg",
    name: "Xander Wyman",
    property: "85",
    location: "Logrono, Spain",
    email: "xander@steex.com",
    contact: "(48) 3877-9000",
    status: "unActive",
    new: true,
  },
  {
    id: 8,
    joining_date: "29 Feb, 2023",
    img: Avatar4,
    img_alt: "avatar-4.jpg",
    name: "Donnell Schultz",
    property: "326",
    location: "Natal, Brazil",
    email: "donnell@steex.com",
    contact: "(51) 3233-7909",
    status: "active",
    new: false,
  },
  {
    id: 9,
    joining_date: "11 Mar, 2023",
    img: Avatar3,
    img_alt: "avatar-3.jpg",
    name: "Jacinthe Will",
    property: "741",
    location: "Brasília, Brazil",
    email: "dianna@steex.com",
    contact: "(33) 3521-6761",
    status: "active",
    new: true,
  },
  {
    id: 10,
    joining_date: "15 Mar, 2023",
    img: Avatar2,
    img_alt: "avatar-2.jpg",
    name: "Josefa Weissnat",
    property: "159",
    location: "California, USA",
    email: "josefaweissnat@steex.com",
    contact: "(53) 3035-3100",
    status: "unActive",
    new: false,
  },
  {
    id: 11,
    joining_date: "17 Mar, 2023",
    img: Avatar6,
    img_alt: "avatar-6.jpg",
    name: "Buck Roberts",
    property: "149",
    location: "Guarulhos, Brazil",
    email: "buckroberts@steex.com",
    contact: "(11) 3885-1022",
    status: "active",
    new: false,
  },
];

export const statusOptions: MenuSelectItemType[] = [
  { label: "Select all", value: "" },
  { label: "Active", value: "active" },
  { label: "UnActive", value: "unActive" },
];
