import { BreadcrumbType } from "@/app/common/types/breadcrumb.type";
import {
  Avatar1,
  Avatar2,
  Avatar3,
  Avatar4,
  Avatar5,
  Avatar6,
  Avatar7,
  Avatar8,
  Avatar9,
  Avatar10,
} from "@/assets/images/users/utils";
import { InstructorDataType } from "@/components/learning/instructors/types";
import { OptionType } from "@/app/common/types/option.type";

export const breadcrumb: BreadcrumbType[] = [
  {
    title: "instructors",
    disabled: false,
  },
  {
    title: "grid-view",
    disabled: true,
  },
];

export const instructorGrid: InstructorDataType[] = [
  {
    id: 1,
    img: Avatar2,
    name: "Ayaan Bowen",
    designation: "Shopify Development",
    email: "ayaanbowen@steex.com",
    experience: "9 Months",
    students: "320",
    contact: "+(152) 15963 24785",
    total_course: "134",
    rating: "4.5",
    status: "active",
  },
  {
    id: 2,
    img: Avatar1,
    name: "Priscilla Takahashi",
    designation: "Project Manager",
    email: "priscilla@steex.com",
    experience: "1 Years",
    students: "159",
    contact: "+(122) 0397 3076",
    total_course: "160",
    rating: "4.8",
    status: "active",
    isChecked: true,
  },
  {
    id: 3,
    img: Avatar3,
    name: "Martin Roth",
    designation: "Graphic Designer",
    email: "martinroth@steex.com",
    experience: "8 Months",
    students: "362",
    contact: "781 789 3874",
    total_course: "362",
    rating: "4.3",
    status: "active",
  },
  {
    id: 4,
    img: Avatar4,
    name: "Jennifer Masten",
    designation: "React Development",
    email: "jennifermasten@steex.com",
    experience: "3 Years",
    students: "321",
    contact: "918 664 0738",
    total_course: "241",
    rating: "4.6",
    status: "active",
  },
  {
    id: 5,
    img: Avatar5,
    name: "Hazel Gordon",
    designation: "Laravel Development",
    email: "hazelgordon@steex.com",
    experience: "5 Years",
    students: "364",
    contact: "617 398 3263",
    total_course: "237",
    rating: "4.8",
    status: "unActive",
  },
  {
    id: 6,
    img: Avatar8,
    name: "Michael Johnson",
    designation: "Flask Development",
    email: "michaeljohnson@steex.com",
    experience: "6 Years",
    students: "84",
    contact: "02261 95 80 88",
    total_course: "174",
    rating: "4.7",
    status: "active",
  },
  {
    id: 7,
    img: Avatar6,
    name: "Angela Fryar",
    designation: "Web Designer",
    email: "angelafryar@steex.com",
    experience: "2 Years",
    students: "146",
    contact: "089 54 77 91",
    total_course: "99",
    rating: "4.9",
    status: "active",
  },
  {
    id: 8,
    img: Avatar7,
    name: "Anthony Gardner",
    designation: "Marketing & Management",
    email: "ayaanbowen@steex.com",
    experience: "7 Months",
    students: "120",
    contact: "09404 91 69 16",
    total_course: "110",
    rating: "4.6",
    status: "active",
  },
  {
    id: 9,
    img: Avatar9,
    name: "James Bradley",
    designation: "Marketing & Management",
    email: "jamesbradley@steex.com",
    experience: "1 Years",
    students: "79",
    contact: "040 67 58 18",
    total_course: "159",
    rating: "4.3",
    status: "active",
    isChecked: true,
  },
  {
    id: 10,
    img: Avatar10,
    name: "Brenda Cornett",
    designation: "Marketing & Management",
    email: "brendacornett@steex.com",
    experience: "2 Years",
    students: "49",
    contact: "03586 68 04 69",
    total_course: "176",
    rating: "4.3",
    status: "active",
  },
  {
    id: 11,
    img: Avatar1,
    name: "Brenda Cornett",
    designation: "Marketing & Management",
    email: "brendacornett@steex.com",
    experience: "5 Years",
    students: "364",
    contact: "03586 68 04 69",
    total_course: "176",
    rating: "4.3",
    status: "active",
  },
];

export const cardOptions: OptionType[] = [
  {
    title: "Edit",
    icon: "ph-pencil",
    value: "edit",
  },
  {
    title: "Delete",
    icon: "ph-trash",
    value: "delete",
  },
];
