import { BreadcrumbType } from "@/app/common/types/breadcrumb.type";
import {
  core,
  flask,
  laravel,
  mysql,
  react,
  shopify,
  sketch,
  tailwindcss,
  webpack,
} from "@/assets/images/learning/utils";
import { Firefox } from "@/assets/images/brands/utils";
import { TableHeaderType } from "@/app/common/types/table.types";
import { CourseListType } from "@/components/learning/courses/listView/types";
import { MenuSelectItemType } from "@/app/common/components/filters/types";

export const listBreadcrumb: BreadcrumbType[] = [
  {
    title: "courses",
    disabled: false,
  },
  {
    title: "list-view",
    disabled: true,
  },
];

export const filters = {
  query: "",
  price: [100, 1000],
  categories: [],
  ratings: [],
};

export const courseListHeader: TableHeaderType[] = [
  { title: "", isCheck: true },
  { title: "Category" },
  { title: "Course Name" },
  { title: "Instructor" },
  { title: "Lessons" },
  { title: "Duration" },
  { title: "Students" },
  { title: "Fees" },
  { title: "Rating" },
  { title: "Status" },
  { title: "Action" },
];

export const coursesList: CourseListType[] = [
  {
    id: 1,
    category: "Laravel Development",
    img: laravel,
    img_alt: "laravel.png",
    name: "Master Laravel for Beginners & Intermediate",
    instructor: "Ophelia Steuber",
    lessons: "57",
    duration: "1 Years",
    students: "84",
    fees: "$220.00",
    rating: "4.4",
    status: "open",
  },
  {
    id: 2,
    category: "PHP Development",
    img: mysql,
    img_alt: "mysql.png",
    name: "Fundamentals of Database Engineering",
    instructor: "Domenic Dach",
    lessons: "87",
    duration: "9 Months",
    students: "320",
    fees: "$99.99",
    rating: "4.9",
    status: "open",
  },
  {
    id: 3,
    category: "Marketing & Management",
    img: Firefox,
    img_alt: "firefox.png",
    name: "Conflict Management with Emotional Intelligence",
    instructor: "Prezy Mark",
    lessons: "43",
    duration: "1 Years",
    students: "159",
    fees: "$214.99",
    rating: "4.8",
    status: "close",
  },
  {
    id: 4,
    category: "Web Design",
    img: tailwindcss,
    img_alt: "tailwindcss.png",
    name: "Tailwind CSS From Scratch",
    instructor: "Nelson Schaden",
    lessons: "101",
    duration: "8 Months",
    students: "362",
    fees: "$301.00",
    rating: "4.2",
    status: "open",
  },
  {
    id: 5,
    category: "Asp.Net Development",
    img: core,
    img_alt: "core.png",
    name: "Asp.Net Core 7 True Ultimate Guide",
    instructor: "Deondre Huel",
    lessons: "49",
    duration: "8 Years",
    students: "321",
    fees: "$674.00",
    rating: "4.6",
    status: "open",
  },
  {
    id: 6,
    category: "Flask Development",
    img: flask,
    img_alt: "flask.png",
    name: "REST APIs with Flask",
    instructor: "Sarai Schmidt",
    lessons: "230",
    duration: "3 Years",
    students: "364",
    fees: "$539.99",
    rating: "4.7",
    status: "close",
  },
  {
    id: 7,
    category: "Laravel Development",
    img: laravel,
    img_alt: "laravel.png",
    name: "Master Laravel for Beginners & Intermediate",
    instructor: "Ophelia Steuber",
    lessons: "57",
    duration: "1 Years",
    students: "84",
    fees: "$220.00",
    rating: "4.4",
    status: "open",
  },
  {
    id: 8,
    category: "Marketing & Management",
    img: webpack,
    img_alt: "webpack.png",
    name: "Digital Marketing",
    instructor: "Nelson Schaden",
    lessons: "93",
    duration: "2 Years",
    students: "146",
    fees: "$149.99",
    rating: "4.8",
    status: "open",
  },
  {
    id: 9,
    category: "Graphic Design",
    img: sketch,
    img_alt: "sketch.png",
    name: "UI/UX Styleguide With Sketch",
    instructor: "Zachary Stokes",
    lessons: "68",
    duration: "7 Months",
    students: "120",
    fees: "$321.99",
    rating: "4.9",
    status: "open",
  },
  {
    id: 10,
    category: "Shopify Development",
    img: shopify,
    img_alt: "shopify.png",
    name: "The Complete Shopify Dropship course",
    instructor: "Ayaan Bowen",
    lessons: "120",
    duration: "1 Years",
    students: "23",
    fees: "$193.00",
    rating: "4.7",
    status: "close",
  },
  {
    id: 11,
    category: "React Development",
    img: react,
    img_alt: "react.png",
    name: "Advanced React and Redux",
    instructor: "Themesbrand",
    lessons: "15",
    duration: "2 Years",
    students: "49",
    fees: "$278.12",
    rating: "4.5",
    status: "open",
  },
];

export const courseOptions: MenuSelectItemType[] = [
  { value: "", label: "Select All" },
  { value: "Marketing & Management", label: "Marketing & Management" },
  { value: "React Development", label: "React Development" },
  { value: "Shopify Development", label: "Shopify Development" },
  { value: "Graphic Design", label: "Graphic Design" },
  { value: "Laravel Development", label: "Laravel Development" },
  { value: "Flask Development", label: "Flask Development" },
  { value: "Web Design", label: "Web Design" },
  { value: "Asp.Net Development", label: "Asp.Net Development" },
  { value: "PHP Development", label: "PHP Development" },
  { value: "Graphic Design", label: "Graphic Design" },
  { value: "Digital Marketing", label: "Digital Marketing" },
  { value: "Data Science", label: "Data Science" },
];

export const ratingOptions: MenuSelectItemType[] = [
  { value: "", label: "Select All" },
  { value: 5, label: "" },
  { value: 4, label: "4 & Up" },
  { value: 3, label: "3 & Up" },
  { value: 2, label: "4 & Up" },
  { value: 1, label: "1 & Up" },
];

export const statusOptions: MenuSelectItemType[] = [
  { value: "", label: "Select Status" },
  { value: "open", label: "Open" },
  { value: "close", label: "Close" },
];
