import { OptionType } from "@/app/common/types/option.type";
import {
  Avatar1,
  Avatar2,
  Avatar3,
  Avatar4,
  Avatar5,
  Avatar6,
  Avatar7,
  Avatar8,
  Avatar9,
  Avatar10,
  DummyUser,
} from "@/assets/images/users/utils";
import {
  EmailChatType,
  ComposeLabelType,
  ComposeListType,
  EmailMenuListItemsType,
  EmailMenuItemType,
  MailBoxType,
} from "@/components/email/types";

export const emailMenuItems: EmailMenuItemType[] = [
  {
    title: "Email",
    value: "email",
    icon: "ph-envelope ph-lg",
  },
  {
    title: "Chat",
    value: "chat",
    to: "/chat",
    icon: "ph-chat-circle-dots ph-lg",
  },
  {
    title: "Meet",
    value: "meet",
    to: "/chat",
    icon: "ph-video-camera ph-lg",
  },
  {
    title: "Storage",
    value: "storage",
    to: "/file-manager",
    icon: "ph-database ph-lg",
  },
];

export const emailMenuListItems: EmailMenuListItemsType[] = [
  {
    src: Avatar1,
    email: "everett@themesbrand.com",
  },
  {
    src: Avatar3,
    email: "johnny@themesbrand.com",
  },
  {
    src: Avatar5,
    email: "michelle@themesbrand.com",
  },
];

export const composeList: ComposeListType[] = [
  {
    id: 1,
    title: "All",
    icon: "ph-envelope ph-lg",
    count: 5,
    value: "all",
  },
  {
    id: 2,
    title: "Inbox",
    icon: "ph-tray ph-lg",
    count: 5,
    value: "inbox",
  },
  {
    id: 3,
    title: "Sent",
    icon: "ph-paper-plane-tilt ph-lg",
    value: "sent",
  },
  {
    id: 4,
    title: "Draft",
    icon: "ph-note-pencil ph-lg",
    value: "draft",
  },
  {
    id: 5,
    title: "Spam",
    icon: "ph-warning ph-lg",
    value: "spam",
  },
  {
    id: 6,
    title: "Trash",
    icon: "ph-trash ph-lg",
    value: "trash",
  },
  {
    id: 7,
    title: "Starred",
    icon: "ph-shield-star ph-lg",
    value: "starred",
  },
  {
    id: 8,
    title: "Important",
    icon: "ph-tag ph-lg",
    value: "important",
  },
];

export const composeLabel: ComposeLabelType[] = [
  {
    id: 1,
    title: "Support",
    count: 3,
    color: "info",
    value: "support",
  },
  {
    id: 2,
    title: "Freelance",
    color: "warning",
    value: "freelance",
  },
  {
    id: 3,
    title: "Social",
    color: "primary",
    value: "social",
  },
  {
    id: 4,
    title: "Friends",
    color: "primary",
    value: "friends",
  },
  {
    id: 5,
    title: "Family",
    count: 2,
    color: "success",
    value: "family",
  },
];

export const emailChats: EmailChatType[] = [
  {
    name: "Scott Median",
    message: "Hello ! are you there?",
    src: Avatar2,
  },
  {
    name: "Julian Rosa",
    message: "What about our next..",
    src: Avatar4,
  },
  {
    name: "David Medina",
    message: "Yeah everything is fine",
    src: Avatar3,
  },
  {
    name: "Jay Baker",
    message: "Wow that's great",
    src: Avatar5,
  },
];

export const mailbox: MailBoxType[] = [
  {
    id: 1,
    forId: "flexCheck20",
    name: "Peter, me",
    number: "(3)",
    subject: "Hello",
    teaser:
      "Trip home from Colombo has been arranged, then Jenna will come get me from Stockholm. :)",
    date: "Mar 6",
    type: "primary",
    category: "all",
    label: "support",
    img: Avatar6,
    isStar: true,
  },
  {
    id: 2,
    unread: true,
    forId: "flexCheck17",
    name: "Susanna",
    number: "(7)",
    subject:
      "Since you asked... and i'm inconceivably bored at the train station",
    badge: "Freelance",
    badgeClass: "warning",
    teaser:
      "Alright thanks. I'll have to re-book that somehow, i'll get back to you.",
    date: "Mar 6",
    type: "primary",
    category: "all",
    label: "friends",
    img: Avatar2,
  },
  {
    id: 3,
    forId: "flexCheck16",
    name: "Web Support Dennis",
    number: "",
    subject: "Re: New mail settings",
    teaser: "Will you answer him asap?",
    date: "Mar 7",
    type: "primary",
    category: "all",
    label: "friends",
    img: Avatar3,
    isStar: true,
  },
  {
    id: 4,
    forId: "flexCheck15",
    name: "me, Peter",
    number: "(2)",
    subject: "Off on Thursday",
    badge: "Support",
    badgeClass: "info",
    teaser:
      "Eff that place, you might as well stay here with us instead! Sent from my iPhone 4  4 mar 2014 at 5:55 pm",
    date: "Mar 4",
    type: "primary",
    category: "all",
    label: "friends",
    img: Avatar4,
  },
  {
    id: 5,
    forId: "flexCheck14",
    name: "Medium",
    number: "",
    subject: "This Week's Top Stories",
    badge: "Social",
    badgeClass: "primary",
    teaser:
      "Our top pick for you on Medium this week The Man Who Destroyed America's Ego",
    date: "Feb 28",
    type: "primary",
    category: "inbox",
    label: "support",
    img: Avatar5,
    isStar: true,
  },
  {
    id: 6,
    forId: "flexCheck13",
    name: "Death to Stock",
    number: "",
    subject: "Montly High-Res Photos",
    teaser:
      "To create this month's pack, we hosted a party with local musician Jared Mahone here in Columbus, Ohio.",
    date: "Feb 28",
    type: "primary",
    category: "inbox",
    label: "friends",
    img: DummyUser,
  },
  {
    id: 7,
    unread: true,
    forId: "flexCheck12",
    name: "Randy, me",
    number: "(5)",
    subject: "Last pic over my village",
    badge: "Family",
    badgeClass: "success",
    teaser:
      "Yeah i'd like that! Do you remember the video you showed me of your train ride between Colombo and Kandy? The one with the mountain view? I would love to see that one again!",
    date: "5:01 am",
    type: "primary",
    category: "all",
    label: "family",
    img: Avatar7,
  },
  {
    id: 8,
    forId: "flexCheck11",
    name: "Andrew Zimmer",
    number: "",
    subject: "Mochila Beta: Subscription Confirme",
    teaser:
      "You've been confirmed! Welcome to the ruling class of the inbox. For your records, here is a copy of the information you submitted to us...",
    date: "Mar 8",
    type: "primary",
    category: "draft",
    label: "social",
    img: Avatar8,
    isStar: true,
  },
  {
    id: 9,
    forId: "flexCheck10",
    name: "Infinity HR",
    number: "",
    subject: "Sveriges Hetaste sommarjobb",
    teaser:
      "Hej Nicklas Sandell! Vi vill bjuda in dig till 'First tour 2014', ett rekryteringsevent som erbjuder jobb på 16 semesterorter iSverige.",
    date: "Mar 8",
    type: "primary",
    category: "starred",
    label: "support",
    img: Avatar9,
    isStar: true,
  },
  {
    id: 10,
    forId: "flexCheck09",
    name: "Revibe",
    number: "",
    subject: "Weekend on Revibe",
    badge: "Friends",
    badgeClass: "danger",
    teaser:
      "Today's Friday and we thought maybe you want some music inspiration for the weekend. Here are some trending tracks and playlists we think you should give a listen!",
    date: "Feb 27",
    type: "primary",
    category: "starred",
    label: "support",
    img: Avatar10,
    isStar: true,
  },
  {
    id: 11,
    forId: "flexCheck08",
    name: "Erik, me",
    number: "(5)",
    subject: "Regarding our meeting",
    teaser: "That's great, see you on Thursday!",
    date: "Feb 24",
    type: "primary",
    category: "inbox",
    label: "social",
    img: Avatar6,
    isStar: true,
  },
  {
    id: 12,
    forId: "flexCheck07",
    name: "KanbanFlow",
    number: "",
    subject: "Task assigned: Clone ARP's website",
    badge: "Social",
    badgeClass: "primary",
    teaser: "You have been assigned a task by Alex@Work on the board Web.",
    date: "Feb 24",
    type: "primary",
    category: "inbox",
    label: "friends",
    img: Avatar7,
    isStar: true,
  },
  {
    id: 13,
    forId: "flexCheck06",
    name: "Tobias Berggren",
    number: "",
    subject: "Let's go fishing!",
    teaser:
      "Hey, You wanna join me and Fred at the lake tomorrow? It'll be awesome.",
    date: "Feb 23",
    type: "primary",
    category: "inbox",
    label: "family",
    img: Avatar8,
    isStar: true,
  },
  {
    id: 14,
    forId: "flexCheck05",
    name: "Charukaw, me",
    number: "(7)",
    subject: "Hey man",
    teaser: "Nah man sorry i don't. Should i get it?",
    date: "Feb 23",
    type: "primary",
    category: "important",
    label: "support",
    img: Avatar9,
  },
  {
    id: 15,
    unread: true,
    forId: "flexCheck04",
    name: "me, Peter",
    number: "(5)",
    subject: "Home again!",
    badge: "Support",
    badgeClass: "info",
    teaser: "That's just perfect! See you tomorrow.",
    date: "Feb 21",
    type: "primary",
    category: "all",
    label: "social",
    img: Avatar10,
  },
  {
    id: 16,
    forId: "flexCheck03",
    name: "Stack Exchange",
    number: "",
    subject: "1 new items in your Stackexchange inbox",
    teaser:
      "The following items were added to your Stack Exchange global inbox since you last checked it.",
    date: "Feb 21",
    type: "primary",
    category: "starred",
    label: "social",
    img: DummyUser,
  },
  {
    id: 17,
    forId: "flexCheck02",
    name: "Google Drive Team",
    number: "",
    subject: "You can now use your storage in GoogleDrive",
    teaser:
      "Hey Nicklas Sandell! Thank you for purchasing extra storage space in Google Drive.",
    date: "Feb 20",
    type: "promotions",
    category: "spam",
    label: "social",
    img: DummyUser,
  },
  {
    id: 18,
    forId: "flexCheck01",
    name: "me, Susanna",
    number: "(11)",
    subject: "Train/Bus",
    teaser:
      "Yes ok, great! I'm not stuck in Stockholm anymore, we're making progress.",
    date: "Feb 19",
    type: "primary",
    category: "sent",
    label: "support",
    img: Avatar6,
    isStar: true,
  },
  {
    id: 19,
    unread: true,
    forId: "flexCheck21",
    name: "Peter, me",
    number: "",
    subject: "Hello",
    teaser:
      "Trip home from Colombo has been arranged, then Jenna will come get me from Stockholm. :)",
    date: "Mar 7",
    type: "social",
    category: "inbox",
    label: "support",
    img: Avatar2,
  },
  {
    id: 20,
    unread: true,
    forId: "flexCheck22",
    name: "me, Susanna",
    number: "(7)",
    subject:
      "Since you asked... and i'm inconceivably bored at the train station",
    badge: "Freelance",
    badgeClass: "warning",
    teaser:
      "Alright thanks. I'll have to re-book that somehow, i'll get back to you.",
    date: "Mar 7",
    type: "social",
    category: "all",
    label: "freelance",
    img: Avatar4,
  },
  {
    id: 21,
    forId: "flexCheck23",
    name: "Web Support Dennis",
    number: "(7)",
    subject: "Re: New mail settings",
    teaser: "Will you answer him asap?",
    date: "Mar 5",
    type: "social",
    category: "trash",
    label: "social",
    img: DummyUser,
  },
  {
    id: 18,
    forId: "flexCheck24",
    name: "me, Susanna",
    number: "",
    subject: "Train/Bus",
    teaser:
      "Yes ok, great! I'm not stuck in Stockholm anymore, we're making progress.",
    date: "Feb 19",
    type: "promotions",
    category: "draft",
    label: "freelance",
    img: Avatar5,
  },
  {
    id: 19,
    forId: "flexCheck25",
    name: "Peter",
    number: "",
    subject: "Home again!",
    badge: "Support - Off on Thursday",
    badgeClass: "info",
    teaser:
      "Eff that place, you might as well stay here with us instead! Sent from my iPhone 4  4 mar 2014 at 5:55 pm",
    date: "Mar 4",
    type: "primary",
    category: "sent",
    label: "support",
    img: Avatar2,
    isStar: true,
  },
];

export const chatBoxOption: OptionType[] = [
  {
    icon: "bx bx-reply",
    title: "Reply",
    value: "reply",
  },
  {
    icon: "bx bx-copy",
    title: "Copy",
    value: "copy",
  },
  {
    icon: "bx bx-trash",
    title: "Delete",
    value: "delete",
  },
];
