import { BreadcrumbType } from "@/app/common/types/breadcrumb.type";
import {
  core,
  flask,
  laravel,
  mysql,
  react,
  shopify,
  sketch,
  tailwindcss,
  webpack,
} from "@/assets/images/learning/utils";

import {
  Avatar1,
  Avatar2,
  Avatar3,
  Avatar4,
  Avatar5,
  Avatar6,
  Avatar7,
  Avatar8,
  Avatar9,
  Avatar10,
} from "@/assets/images/users/utils";
import { Firefox } from "@/assets/images/brands/utils";
import { CourseGridType } from "@/components/learning/courses/gridView/types";
import { OptionType } from "@/app/common/types/option.type";

export const gridBreadcrumb: BreadcrumbType[] = [
  {
    title: "courses",
    disabled: false,
  },
  {
    title: "grid-view",
    disabled: true,
  },
];

export const coursesGrid: CourseGridType[] = [
  {
    id: 1,
    img: react,
    badgeText: "intermediate",
    backgroundColor: "bg-info-subtle",
    isBookmark: "",
    name: "advanced React and Redux",
    category: "React Development",
    duration: "6 Months",
    students: 256,
    lessons: 15,
    userImg: Avatar2,
    instructor: "Themesbrand",
    fees: "$220.00",
    rating: "4.4",
    status: "Open",
  },
  {
    id: 2,
    img: shopify,
    badgeText: "beginner",
    backgroundColor: "bg-success-subtle",
    isBookmark: "active",
    name: "The Complete Shopify Dropship course",
    category: "Shopify Development",
    duration: "1 Years",
    students: 120,
    lessons: 68,
    userImg: Avatar3,
    instructor: "Ayaan Bowen",
    fees: "$99.99",
    rating: "4.9",
    status: "Open",
  },
  {
    id: 3,
    img: sketch,
    badgeText: "advance",
    backgroundColor: "bg-warning-subtle",
    isBookmark: "active",
    name: "UI/UX Style Guide With Sketch",
    category: "Graphic Design",
    duration: "7 Months",
    students: 120,
    lessons: 68,
    userImg: Avatar6,
    instructor: "Zachary Stokes",
    fees: "$214.99",
    rating: "4.8",
    status: "Close",
  },
  {
    id: 4,
    img: webpack,
    badgeText: "intermediate",
    backgroundColor: "bg-primary-subtle",
    isBookmark: "",
    name: "Digital Marketing",
    category: "Marketing & Management",
    duration: "2 Years",
    students: 146,
    lessons: 93,
    userImg: Avatar4,
    instructor: "Nelson Schaden",
    fees: "$301.00",
    rating: "4.2",
    status: "Open",
  },
  {
    id: 5,
    img: laravel,
    badgeText: "advance",
    backgroundColor: "bg-danger-subtle",
    isBookmark: "active",
    name: "Master Laravel for Beginners & Intermediate",
    category: "Laravel Development",
    duration: "1 Years",
    students: 84,
    lessons: 57,
    userImg: Avatar9,
    instructor: "Ophelia Steuber",
    fees: "$674.00",
    rating: "4.6",
    status: "Open",
  },
  {
    id: 6,
    img: flask,
    badgeText: "beginner",
    backgroundColor: "bg-dark-subtle",
    isBookmark: "active",
    name: "REST APIs With Flask",
    category: "Flask Development",
    duration: "3 Years",
    students: 364,
    lessons: 230,
    userImg: Avatar1,
    instructor: "Sarai Schmidt",
    fees: "$539.99",
    rating: "4.7",
    status: "Close",
  },
  {
    id: 7,
    img: core,
    badgeText: "intermediate",
    backgroundColor: "bg-primary-subtle",
    isBookmark: "",
    name: "Asp.Net Core 7 True Ultimate Guide",
    category: "Asp.Net Development",
    duration: "8 Years",
    students: 321,
    lessons: 49,
    userImg: Avatar10,
    instructor: "Deondre Huel",
    fees: "$220.00",
    rating: "4.4",
    status: "Open",
  },
  {
    id: 8,
    img: tailwindcss,
    badgeText: "beginner",
    backgroundColor: "bg-info-subtle",
    isBookmark: "active",
    name: "Tailwind CSS From Scratch",
    category: "Web Design",
    duration: "8 Months",
    students: 362,
    lessons: 101,
    userImg: Avatar8,
    instructor: "Nelson Schaden",
    fees: "$149.99",
    rating: "4.8",
    status: "Open",
  },
  {
    id: 9,
    img: Firefox,
    badgeText: "advance",
    backgroundColor: "bg-danger-subtle",
    isBookmark: "active",
    name: "Conflict Management with Emotional Intelligence",
    category: "Marketing & Management",
    duration: "1 Years",
    students: 159,
    lessons: 43,
    userImg: Avatar7,
    instructor: "Prezy Mark",
    fees: "$321.99",
    rating: "4.9",
    status: "Open",
  },
  {
    id: 10,
    img: mysql,
    badgeText: "intermediate",
    backgroundColor: "bg-info-subtle",
    isBookmark: "active",
    name: "Fundamentals of Database Engineering",
    category: "PHP Development",
    duration: "9 Months",
    students: 320,
    lessons: 87,
    userImg: Avatar5,
    instructor: "Domenic Dach",
    fees: "$193.00",
    rating: "4.7",
    status: "Close",
  },
];

export const cardOptions: OptionType[] = [
  {
    title: "Overview",
    value: "overview",
    icon: "ph-eye ph-lg",
  },
  {
    title: "Edit",
    value: "edit",
    icon: "ph-pencil ph-lg",
  },
  {
    title: "Delete",
    value: "delete",
    icon: "ph-trash ph-lg",
  },
];

export const includedCourses = [
  {
    title: "Lessons",
    value: 35,
    icon: "ph-book-open",
  },
  {
    title: "Duration",
    value: "6 Months",
    icon: "ph-timer",
  },
  {
    title: "Skills",
    value: "Beginner",
    icon: "ph-chart-bar",
  },
  {
    title: "Language",
    value: "English",
    icon: "ph-book-open",
  },
  {
    title: "Certificate",
    value: "Yes",
    icon: "ph-article",
  },
];
