import {
  img01,
  img02,
  img03,
  img04,
  img05,
  img06,
  img08,
} from "@/assets/images/real-estate/utils";
import { PropertyType } from "@/components/realEstate/types";

export const properties: PropertyType[] = [
  {
    id: 1,
    type: "Residency",
    title: "Duplex Square Valley",
    img: img05,
    img_alt: "img-05.jpg",
    location: "Distrito Federal, Brazil",
    bedroom: "3",
    bathroom: "2",
    area: "1039",
    rating: "4.4",
    price: "2579.31",
    isBookmark: false,
    agent: "Buck Roberts",
    requirement: "Rent",
  },
  {
    id: 2,
    type: "Villa",
    title: "Whitepace Vintage Villa",
    img: img04,
    img_alt: "img-04.jpg",
    location: "Cantabria, Spain",
    bedroom: "4",
    bathroom: "2",
    area: "1754",
    rating: "4.9",
    price: "3495.76",
    isBookmark: true,
    agent: "Axel Kozey",
    requirement: "Sale",
  },
  {
    id: 3,
    type: "Villa",
    title: "Crystal House",
    img: img06,
    img_alt: "img-06.jpg",
    location: "Guipuzcua, Spain",
    bedroom: "2",
    bathroom: "1",
    area: "1039",
    rating: "4.8",
    price: "1249.99",
    isBookmark: true,
    agent: "Uriel King",
    requirement: "Sale",
  },
  {
    id: 4,
    type: "Apartment",
    title: "Small house on an autumn’s day",
    img: img08,
    img_alt: "img-08.jpg",
    location: "West Midland, United Kingdom",
    bedroom: "4",
    bathroom: "2",
    area: "1796",
    rating: "4.9",
    price: "3895.39",
    isBookmark: false,
    agent: "Josefa Weissnat",
    requirement: "Sale",
  },
  {
    id: 5,
    type: "Villa",
    title: "Swimming pool side of the residential Ascot home.",
    img: img08,
    img_alt: "img-08.jpg",
    location: "Estado de Mexico, Mexico",
    bedroom: "4",
    bathroom: "2",
    area: "1145",
    rating: "4.5",
    price: "1452.39",
    isBookmark: true,
    agent: "Federico Hand",
    requirement: "Rent",
  },
  {
    id: 6,
    type: "Villa",
    title: "Crystal House",
    img: img06,
    img_alt: "img-06.jpg",
    location: "Guipuzcua, Spain",
    bedroom: "2",
    bathroom: "1",
    area: "1039",
    rating: "4.8",
    price: "1249.99",
    isBookmark: false,
    agent: "Jerry Emard",
    requirement: "Rent",
  },
  {
    id: 7,
    type: "Residency",
    title: "Duplex Square Valley",
    img: img05,
    img_alt: "img-05.jpg",
    location: "Distrito Federal, Brazil",
    bedroom: "3",
    bathroom: "2",
    area: "1039",
    rating: "4.4",
    price: "2579.31",
    isBookmark: false,
    agent: "Buck Roberts",
    requirement: "Rent",
  },
  {
    id: 8,
    type: "Villa",
    title: "Whitepace Vintage Villa",
    img: img04,
    img_alt: "img-04.jpg",
    location: "Cantabria, Spain",
    bedroom: "4",
    bathroom: "2",
    area: "1754",
    rating: "4.9",
    price: "3495.76",
    isBookmark: true,
    agent: "Axel Kozey",
    requirement: "Sale",
  },
  {
    id: 9,
    type: "Apartment",
    title: "Vintage Apartment",
    img: img03,
    img_alt: "img-03.jpg",
    location: "Minas Gerais, Brazil",
    bedroom: "2",
    bathroom: "1",
    area: "1025",
    rating: "4.7",
    price: "1249.99",
    isBookmark: false,
    agent: "Domenic Dach",
    requirement: "Rent",
  },
  {
    id: 10,
    type: "Residency",
    title: "Classic White House",
    img: img02,
    img_alt: "img-02.jpg",
    location: "Minas Gerais, Brazil",
    bedroom: "3",
    bathroom: "2",
    area: "1324",
    rating: "4.5",
    price: "3698.99",
    isBookmark: false,
    agent: "Jerry Emard",
    requirement: "Rent",
  },
  {
    id: 11,
    type: "Villa",
    title: "The Country House",
    img: img01,
    img_alt: "img-01.jpg",
    location: "West Midlands, United Kingdom",
    bedroom: "2",
    bathroom: "1",
    area: "1458",
    rating: "4.5",
    price: "2451.39",
    isBookmark: true,
    agent: "Josefa Weissnat",
    requirement: "Sale",
  },
];
