import { BreadcrumbType } from "@/app/common/types/breadcrumb.type";
import {
  Img1,
  Img2,
  Img3,
  Img4,
  Img5,
  Img6,
  Img7,
  Img8,
  Img9,
  Img10,
  Img11,
  Img12,
} from "@/assets/images/products/utils";
import {
  ProductGridType,
  CategoryType,
  FilterType,
} from "@/components/eCommerce/productGrid/types";

export const productGridBreadcrumb: BreadcrumbType[] = [
  {
    title: "ecommerce",
    disabled: false,
  },
  {
    title: "products-grid",
    disabled: true,
  },
];

export const filter: FilterType = {
  query: "",
  category: "",
  price: [100, 1000],
  color: "",
  brands: [],
  discounts: [],
};

export const categoryOptions: CategoryType[] = [
  { title: "All" },
  { title: "Appliances" },
  { title: "Automotive Accessories" },
  { title: "Electronics" },
  { title: "Fashion", count: 7 },
  { title: "Furniture" },
  { title: "Grocery" },
  { title: "Headphones", count: 2 },
  { title: "Kids" },
  { title: "Luggage", count: 1 },
  { title: "Sports", count: 1 },
  { title: "Watches", count: 1 },
];

export const colors = [
  {
    title: "Blue",
    color: "primary",
  },
  {
    title: "Dark",
    color: "secondary",
  },
  {
    title: "Green",
    color: "success",
  },
  {
    title: "Red",
    color: "danger",
  },
  {
    title: "Black",
    color: "black",
  },
  {
    title: "Yellow",
    color: "warning",
  },
  {
    title: "Cyan",
    color: "info",
  },
];

export const brands = [
  { title: "Boat" },
  { title: "OnePlus" },
  { title: "RealMe" },
  { title: "Sony" },
  { title: "JBL" },
];

export const discountOptions = [
  { title: "50% or more", value: 50 },
  { title: "40% or more", value: 40 },
  { title: "30% or more", value: 30 },
  { title: "20% or more", value: 20 },
  { title: "10% or more", value: 10 },
  { title: "Less than 10%", value: 0 },
];

export const productsGrid: ProductGridType[] = [
  {
    id: 1,
    img: Img1,
    img_alt: "img-1.png",
    title: "Cotton collar tshirts for men",
    category: "Fashion",
    stock: "12",
    price: "215.00",
    discount: 25,
    orders: "06",
    ratings: "4.9",
    publish: "12 Oct, 2022",
  },
  {
    id: 2,
    img: Img2,
    img_alt: "img-2.png",
    title: "Like style travel black handbag",
    category: "Luggage",
    stock: "06",
    price: "160.00",
    discount: 0,
    orders: "02",
    ratings: "4.3",
    publish: "06 Jan, 2023",
  },
  {
    id: 3,
    img: Img3,
    img_alt: "img-3.png",
    title: "Fossil Gen 5E Smart Watch",
    category: "Watches",
    stock: "19",
    price: "120.00",
    discount: 42,
    orders: "21",
    ratings: "4.3",
    publish: "26 Mar, 2021",
  },
  {
    id: 4,
    img: Img4,
    img_alt: "img-4.png",
    title: "Super Bass Blutooth wireless headphone",
    category: "Headphones",
    stock: "23",
    price: "180.00",
    discount: 0,
    orders: "19",
    ratings: "4.1",
    publish: "19 Apr, 2021",
  },
  {
    id: 5,
    img: Img5,
    img_alt: "img-5.png",
    title: "Willage Volleyball Ball Size 4",
    category: "Sports",
    stock: "30",
    price: "99.00",
    discount: 10,
    orders: "21",
    ratings: "4.0",
    publish: "30 Mar, 2021",
  },
  {
    id: 6,
    img: Img6,
    img_alt: "img-6.png",
    title: "Blive Printed Men Round Neck",
    category: "Fashion",
    stock: "35",
    price: "250.00",
    discount: 0,
    orders: "02",
    ratings: "3.8",
    publish: "12 Oct, 2021",
  },
  {
    id: 7,
    img: Img7,
    img_alt: "img-7.png",
    title: "Cotton collar tshirts for men",
    category: "Fashion",
    stock: "12",
    price: "180.00",
    discount: 0,
    orders: "10",
    ratings: "4.0",
    publish: "15 May, 2021",
  },
  {
    id: 8,
    img: Img8,
    img_alt: "img-8.png",
    title: "Full Sleeve Solid Men Sweatshirt/Hoody",
    category: "Fashion",
    stock: "20",
    price: "260.00",
    discount: 12,
    orders: "20",
    ratings: "4.1",
    publish: "21 Jun, 2021",
  },
  {
    id: 9,
    img: Img10,
    img_alt: "img-10.png",
    title: "Men's Round Neck Half Sleeves Solid T-Shirt",
    category: "Fashion",
    stock: "21",
    price: "160.00",
    discount: 0,
    orders: "08",
    ratings: "4.4",
    publish: "15 Jan, 2021",
  },
  {
    id: 10,
    img: Img9,
    img_alt: "img-9.png",
    title: "Flip-Flops and House Slippers",
    category: "Footwear",
    stock: "30",
    price: "150.00",
    discount: 0,
    orders: "10",
    ratings: "4.2",
    publish: "06 Jan, 2023",
  },
  {
    id: 11,
    img: Img11,
    img_alt: "img-11.png",
    title: "Jeans blue men boxer",
    category: "Fashion",
    stock: "50",
    price: "97.99",
    discount: 25,
    orders: "51",
    ratings: "3.9",
    publish: "12 Oct, 2021",
  },
  {
    id: 12,
    img: Img12,
    img_alt: "img-12.png",
    title: "MAG back to the future shoes",
    category: "Footwear",
    stock: "06",
    price: "274.99",
    discount: 0,
    orders: "06",
    ratings: "4.2",
    publish: "06 Jan, 2021",
  },
  {
    id: 13,
    img: Img4,
    img_alt: "img-4.png",
    title: "Super Bass Blutooth wireless headphone",
    category: "Headphones",
    stock: "23",
    price: "180.00",
    discount: 0,
    orders: "19",
    ratings: "4.1",
    publish: "19 Apr, 2021",
  },
  {
    id: 14,
    img: Img7,
    img_alt: "img-7.png",
    title: "Cotton collar tshirts for men",
    category: "Fashion",
    stock: "12",
    price: "180.00",
    discount: 0,
    orders: "10",
    ratings: "4.0",
    publish: "15 May, 2021",
  },
];
